/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "C:\\Users\\Administrator\\Desktop\\新建文件夹\\新建文件夹\\23 - 个人博客\\pengBlog\\blog\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "C:\\Users\\Administrator\\Desktop\\新建文件夹\\新建文件夹\\23 - 个人博客\\pengBlog\\blog\\node_modules\\@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m2 from "C:\\Users\\Administrator\\Desktop\\新建文件夹\\新建文件夹\\23 - 个人博客\\pengBlog\\blog\\node_modules\\@vuepress\\plugin-medium-zoom\\clientRootMixin.js"
import m3 from "C:\\Users\\Administrator\\Desktop\\新建文件夹\\新建文件夹\\23 - 个人博客\\pengBlog\\blog\\node_modules\\@vuepress\\plugin-nprogress\\clientRootMixin.js"
import m4 from "C:\\Users\\Administrator\\Desktop\\新建文件夹\\新建文件夹\\23 - 个人博客\\pengBlog\\blog\\node_modules\\vuepress-plugin-smooth-scroll\\lib\\clientRootMixin.js"
import m5 from "C:\\Users\\Administrator\\Desktop\\新建文件夹\\新建文件夹\\23 - 个人博客\\pengBlog\\blog\\node_modules\\vuepress-plugin-helper-live2d\\lib\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3,
  m4,
  m5
]