/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Nginx": {
      "key": "Nginx",
      "scope": "tags",
      "path": "/tag/Nginx/",
      "pageKeys": [
        "v-3be70d68"
      ]
    },
    "JS": {
      "key": "JS",
      "scope": "tags",
      "path": "/tag/JS/",
      "pageKeys": [
        "v-0487c22c",
        "v-37babdcc",
        "v-3f0a4d6c",
        "v-52e43cac",
        "v-3e0b82e8",
        "v-68d001ac",
        "v-050d196c",
        "v-5153ea4c",
        "v-4f3cb5cc",
        "v-0e73dd8c",
        "v-383f658c",
        "v-53f27d28",
        "v-4b0d9d4c",
        "v-8836c428",
        "v-3c6a21ec",
        "v-5bc2b94c",
        "v-9d1e0468",
        "v-0f7b38ec",
        "v-608444a8",
        "v-6076798c"
      ]
    },
    "HTML": {
      "key": "HTML",
      "scope": "tags",
      "path": "/tag/HTML/",
      "pageKeys": [
        "v-44469d68",
        "v-6cff95ac",
        "v-482e164c"
      ]
    },
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-142d3a2c",
        "v-0171c328",
        "v-02f0d94c"
      ]
    },
    "Cookie": {
      "key": "Cookie",
      "scope": "tags",
      "path": "/tag/Cookie/",
      "pageKeys": [
        "v-07244dec"
      ]
    },
    "VUE": {
      "key": "VUE",
      "scope": "tags",
      "path": "/tag/VUE/",
      "pageKeys": [
        "v-38d26b68",
        "v-77f6b28c",
        "v-2c495c28",
        "v-111e8ce8",
        "v-7bb2ed28",
        "v-3cfecf28",
        "v-662f26ac",
        "v-76e6d96c",
        "v-95cc93e8"
      ]
    },
    "npm": {
      "key": "npm",
      "scope": "tags",
      "path": "/tag/npm/",
      "pageKeys": [
        "v-f9134568",
        "v-6417f22c"
      ]
    },
    "运算符": {
      "key": "运算符",
      "scope": "tags",
      "path": "/tag/运算符/",
      "pageKeys": [
        "v-59aad54c"
      ]
    },
    "组件": {
      "key": "组件",
      "scope": "tags",
      "path": "/tag/组件/",
      "pageKeys": [
        "v-45cb124c"
      ]
    },
    "正则": {
      "key": "正则",
      "scope": "tags",
      "path": "/tag/正则/",
      "pageKeys": [
        "v-411de22c"
      ]
    }
  },
  "categories": {
    "问题集中营": {
      "key": "问题集中营",
      "scope": "categories",
      "path": "/categories/问题集中营/",
      "pageKeys": [
        "v-3be70d68"
      ]
    },
    "前端小笔记": {
      "key": "前端小笔记",
      "scope": "categories",
      "path": "/categories/前端小笔记/",
      "pageKeys": [
        "v-0487c22c",
        "v-37babdcc",
        "v-3f0a4d6c",
        "v-52e43cac",
        "v-44469d68",
        "v-3e0b82e8",
        "v-142d3a2c",
        "v-68d001ac",
        "v-0171c328",
        "v-050d196c",
        "v-5153ea4c",
        "v-4f3cb5cc",
        "v-0e73dd8c",
        "v-383f658c",
        "v-4b0d9d4c",
        "v-8836c428",
        "v-3c6a21ec",
        "v-5bc2b94c",
        "v-0f7b38ec",
        "v-608444a8",
        "v-59aad54c",
        "v-6076798c"
      ]
    },
    "Cookie": {
      "key": "Cookie",
      "scope": "categories",
      "path": "/categories/Cookie/",
      "pageKeys": [
        "v-07244dec"
      ]
    },
    "排序": {
      "key": "排序",
      "scope": "categories",
      "path": "/categories/排序/",
      "pageKeys": [
        "v-53f27d28"
      ]
    },
    "VUE": {
      "key": "VUE",
      "scope": "categories",
      "path": "/categories/VUE/",
      "pageKeys": [
        "v-38d26b68",
        "v-77f6b28c",
        "v-2c495c28",
        "v-111e8ce8",
        "v-7bb2ed28",
        "v-3cfecf28",
        "v-662f26ac",
        "v-76e6d96c",
        "v-95cc93e8"
      ]
    },
    "Promise": {
      "key": "Promise",
      "scope": "categories",
      "path": "/categories/Promise/",
      "pageKeys": [
        "v-9d1e0468"
      ]
    },
    "CSS": {
      "key": "CSS",
      "scope": "categories",
      "path": "/categories/CSS/",
      "pageKeys": [
        "v-02f0d94c"
      ]
    },
    "npm": {
      "key": "npm",
      "scope": "categories",
      "path": "/categories/npm/",
      "pageKeys": [
        "v-f9134568",
        "v-6417f22c"
      ]
    },
    "组件": {
      "key": "组件",
      "scope": "categories",
      "path": "/categories/组件/",
      "pageKeys": [
        "v-45cb124c"
      ]
    },
    "正则": {
      "key": "正则",
      "scope": "categories",
      "path": "/categories/正则/",
      "pageKeys": [
        "v-411de22c"
      ]
    },
    "HTML": {
      "key": "HTML",
      "scope": "categories",
      "path": "/categories/HTML/",
      "pageKeys": [
        "v-6cff95ac",
        "v-482e164c"
      ]
    }
  },
  "timeline": {}
}